/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScoreEntry = IDL.Record({
  'user' : IDL.Principal,
  'highScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(ScoreEntry)], ['query']),
  'getScore' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScoreEntry = IDL.Record({
    'user' : IDL.Principal,
    'highScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(ScoreEntry)], ['query']),
    'getScore' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };